export const RajasthanImages ={
    d1 : require('./Rajasthan1.png').default,
    d2 : require('./Rajaasthan2.png').default,
    db1 : require('./Rajasthan3.png').default,
    db2 : require('./Rajasthan Food1.png').default,
    dc1 : require('./Rajasthan food2.png').default,
    dc2 : require('./cult2.jpg').default,
    dh1 : require('./food1.jpg').default,
    dh2 : require('./food2.jpg').default,
    dp1 : require('./pack1.jpg').default,
    dp2 : require('./pack2.jpg').default,
    dp3 : require('./pack3.jpg').default,
    dp4 : require('./pack4.jpg').default,
    do1 : require('./only1.jpg').default,
    do2 : require('./only2.jpg').default,
}