export const UttarakhandImages ={
    d1 : require('./culture1.jpg').default,
    d2 : require('./culture2.jpg').default,
    db1 : require('./nature1.jpg').default,
    db2 : require('./nature2.jpg').default,
    dc1 : require('./onlyk1.jpg').default,
    dc2 : require('./onlyk2.jpg').default,
    dh1 : require('./pack1.jpg').default,
    dh2 : require('./pack2.jpg').default,
    dp1 : require('./pack3.jpg').default,
    dp2 : require('./pack4.jpg').default,
    dp3 : require('./port1.jpg').default,
    dp4 : require('./port2.jpg').default,
    do1 : require('./trek1.jpg').default,
    do2 : require('./trek2.jpg').default,
}